version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: udyam_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: udyamdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: udyam_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build: ./frontend
    container_name: udyam_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000

volumes:
  postgres_data:
